services:
  parser:
    platform: linux/amd64
    image: ghcr.io/jacobmgardiner/flight-log-parser:1.0.0
    # pull_policy: always   # uncomment if you always want the latest for this tag
    environment:
      NODE_ENV: production
      SDK_KEY: ${SDK_KEY}
      MAX_CONCURRENCY: ${MAX_CONCURRENCY:-2}
      PARSE_TIMEOUT_MS: ${PARSE_TIMEOUT_MS:-180000}
      RATE_WINDOW_MS: ${RATE_WINDOW_MS:-60000}
      RATE_MAX: ${RATE_MAX:-30}
      TRUST_PROXY: ${TRUST_PROXY:-1}
      PORT: 8080
    ports:
      - "${PORT:-8787}:8080"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: unless-stopped
