version: "3.9"

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJI_REF: ${DJI_REF:-v1.0.6}
    image: flight-parser-svc:local
    environment:
      NODE_ENV: production
      SDK_KEY: ${SDK_KEY}
      MAX_CONCURRENCY: ${MAX_CONCURRENCY:-2}
      PARSE_TIMEOUT_MS: ${PARSE_TIMEOUT_MS:-180000}
      RATE_WINDOW_MS: ${RATE_WINDOW_MS:-60000}
      RATE_MAX: ${RATE_MAX:-30}
      TRUST_PROXY: ${TRUST_PROXY:-1}
      PORT: 8080
    ports:
      - "${PORT:-8787}:8080"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    # Uncomment to cap resources during local tests
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 1g
